#!/bin/sh
# Borrar logs apache2
# rm -f /usr/local/apache2/logs/httpd.pid

echo "Iniciando SSH y Apache"
# service apache2 start
# exec apache2 -D FOREGROUND 
service ssh start
echo "Iniciando apache"
apachectl -D FOREGROUND